/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teste2;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Nathália
 */
public class Trabalho2TelaInicial2 extends javax.swing.JFrame {
    BufferedImage image;
    int w,h,D0,opcao,nv,W;
    
    /**
     * Creates new form Trabalho2TelaInicial
     */
    public Trabalho2TelaInicial2() {
        initComponents();
    }
    
    class filtrocustomizado extends javax.swing.filechooser.FileFilter{
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".jpg");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "(*.jpg)";
        }
    } 
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filechooser = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        okbuttonD0 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ValorD0 = new javax.swing.JFormattedTextField();
        jDialog2 = new javax.swing.JDialog();
        OKButtonD0n = new javax.swing.JButton();
        D0n = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        D0Text = new javax.swing.JTextField();
        WText2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        okbuttonD0W = new javax.swing.JButton();
        jDialog4 = new javax.swing.JDialog();
        D0Wn = new javax.swing.JTextField();
        WText = new javax.swing.JTextField();
        nW = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        okbuttonD0Wn = new javax.swing.JButton();
        Espectro = new javax.swing.JInternalFrame();
        CarregaIm = new javax.swing.JButton();
        ImagemOriginal = new javax.swing.JInternalFrame();
        ResultadoImagem = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Filtros = new javax.swing.JMenu();
        PassaBaixaId = new javax.swing.JMenuItem();
        PassaBaixaButter = new javax.swing.JMenuItem();
        PassaBaixaGauss = new javax.swing.JMenuItem();
        PassaAltaId = new javax.swing.JMenuItem();
        PassaAltaButter = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Laplac = new javax.swing.JMenuItem();
        Unshar = new javax.swing.JMenuItem();
        BandRejectId = new javax.swing.JMenuItem();
        BandRejectButter = new javax.swing.JMenuItem();
        BandRejectGauss = new javax.swing.JMenuItem();
        BandPassId = new javax.swing.JMenuItem();
        BandPassButter = new javax.swing.JMenuItem();
        BandPassGauss = new javax.swing.JMenuItem();

        filechooser.setFileFilter(new filtrocustomizado());

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDialog1.setTitle("d0");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog1.setPreferredSize(new java.awt.Dimension(400, 300));

        okbuttonD0.setText("ok");
        okbuttonD0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonD0ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("D0");

        ValorD0.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        ValorD0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorD0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(okbuttonD0))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorD0, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ValorD0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(okbuttonD0)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jDialog2.setMinimumSize(new java.awt.Dimension(400, 300));

        OKButtonD0n.setText("OK");
        OKButtonD0n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonD0nActionPerformed(evt);
            }
        });

        jLabel1.setText("D0");

        jLabel2.setText("n");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OKButtonD0n, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(D0n)
                    .addComponent(n))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D0n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(OKButtonD0n)
                .addGap(78, 78, 78))
        );

        jDialog3.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("D0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("W");

        okbuttonD0W.setText("OK");
        okbuttonD0W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonD0WActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog3Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okbuttonD0W)
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(D0Text, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(WText2))))
                .addGap(155, 155, 155))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D0Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(okbuttonD0W)
                .addGap(46, 46, 46))
        );

        jDialog4.setMinimumSize(new java.awt.Dimension(400, 300));

        WText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("D0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("W");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("n");

        okbuttonD0Wn.setText("OK");
        okbuttonD0Wn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonD0WnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okbuttonD0Wn)
                    .addGroup(jDialog4Layout.createSequentialGroup()
                        .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nW, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(WText)
                            .addComponent(D0Wn))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D0Wn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(okbuttonD0Wn)
                .addGap(40, 40, 40))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRABALHO 2");

        Espectro.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Espectro.setVisible(true);

        javax.swing.GroupLayout EspectroLayout = new javax.swing.GroupLayout(Espectro.getContentPane());
        Espectro.getContentPane().setLayout(EspectroLayout);
        EspectroLayout.setHorizontalGroup(
            EspectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );
        EspectroLayout.setVerticalGroup(
            EspectroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        CarregaIm.setText("Carrega Imagem");
        CarregaIm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregaImActionPerformed(evt);
            }
        });

        ImagemOriginal.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        ImagemOriginal.setVisible(true);

        javax.swing.GroupLayout ImagemOriginalLayout = new javax.swing.GroupLayout(ImagemOriginal.getContentPane());
        ImagemOriginal.getContentPane().setLayout(ImagemOriginalLayout);
        ImagemOriginalLayout.setHorizontalGroup(
            ImagemOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );
        ImagemOriginalLayout.setVerticalGroup(
            ImagemOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ResultadoImagem.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        ResultadoImagem.setVisible(true);

        javax.swing.GroupLayout ResultadoImagemLayout = new javax.swing.GroupLayout(ResultadoImagem.getContentPane());
        ResultadoImagem.getContentPane().setLayout(ResultadoImagemLayout);
        ResultadoImagemLayout.setHorizontalGroup(
            ResultadoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );
        ResultadoImagemLayout.setVerticalGroup(
            ResultadoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        Filtros.setText("Filtros");

        PassaBaixaId.setText("Passa-baixa Ideal");
        PassaBaixaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassaBaixaIdActionPerformed(evt);
            }
        });
        Filtros.add(PassaBaixaId);

        PassaBaixaButter.setText("Passa-baixa Butterworth");
        PassaBaixaButter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassaBaixaButterActionPerformed(evt);
            }
        });
        Filtros.add(PassaBaixaButter);

        PassaBaixaGauss.setText("Passa-baixa Gaussiano");
        PassaBaixaGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassaBaixaGaussActionPerformed(evt);
            }
        });
        Filtros.add(PassaBaixaGauss);

        PassaAltaId.setText("Passa-alta Ideal");
        PassaAltaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassaAltaIdActionPerformed(evt);
            }
        });
        Filtros.add(PassaAltaId);

        PassaAltaButter.setText("Passa-alta Butterworth");
        PassaAltaButter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassaAltaButterActionPerformed(evt);
            }
        });
        Filtros.add(PassaAltaButter);

        jMenuItem6.setText("Passa-alta Gaussiano");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Filtros.add(jMenuItem6);

        Laplac.setText("Laplaciano");
        Laplac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaplacActionPerformed(evt);
            }
        });
        Filtros.add(Laplac);

        Unshar.setText("Usharpen");
        Unshar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnsharActionPerformed(evt);
            }
        });
        Filtros.add(Unshar);

        BandRejectId.setText("Band-Reject Ideal");
        BandRejectId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandRejectIdActionPerformed(evt);
            }
        });
        Filtros.add(BandRejectId);

        BandRejectButter.setText("Band-Reject Butterworth");
        BandRejectButter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandRejectButterActionPerformed(evt);
            }
        });
        Filtros.add(BandRejectButter);

        BandRejectGauss.setText("Band-Reject Gaussiano");
        BandRejectGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandRejectGaussActionPerformed(evt);
            }
        });
        Filtros.add(BandRejectGauss);

        BandPassId.setText("Band-Pass Ideal");
        BandPassId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandPassIdActionPerformed(evt);
            }
        });
        Filtros.add(BandPassId);

        BandPassButter.setText("Band-Pass Butterworth");
        BandPassButter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandPassButterActionPerformed(evt);
            }
        });
        Filtros.add(BandPassButter);

        BandPassGauss.setText("Band-Pass Gaussiano");
        BandPassGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandPassGaussActionPerformed(evt);
            }
        });
        Filtros.add(BandPassGauss);

        jMenuBar1.add(Filtros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CarregaIm, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImagemOriginal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Espectro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResultadoImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(CarregaIm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ResultadoImagem, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Espectro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagemOriginal))
                .addGap(0, 278, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void CarregaImActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregaImActionPerformed
        // TODO add your handling code here:
       String local;
       int returnVal = filechooser.showOpenDialog(this);
       if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = filechooser.getSelectedFile();
        
          // What to do with the file, e.g. display it in a TextArea
          local = file.getAbsolutePath();
          //carregar imagem no primeiro quadrinho
            if(local != null){
                image = Imagem.loadImage(local);
                w = image.getWidth();  
                h = image.getHeight();  
        
                Graphics2D g = (Graphics2D)ImagemOriginal.getRootPane().getGraphics();  
                // Now draw the image  
                g.drawImage(image, null, 0, 0);
            }
            else
                JOptionPane.showMessageDialog(null, "Sem arquivo");
           } else {
            System.out.println("File access cancelled by user.");
        } 
        
    }//GEN-LAST:event_CarregaImActionPerformed

    private void UnsharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnsharActionPerformed
        // TODO add your handling code here:
        if(image != null){
            int [] dft = new int [h*w];
            int cod = 7;
            int [] argb = new int [h*w];
            int [] img2 = new int [h*w];
            BufferedImage imageaux = image;  
            image.getRGB(0, 0, w, h, argb, 0, w);
        
            img2 = ConverteCinza.imageToGray(argb);
            dft = DFT2.DFTfunc(img2, w, h,cod,5,0,2,0,0);
            imageaux.setRGB(0, 0, w, h, dft , 0, w);
            Graphics2D g = (Graphics2D)ResultadoImagem.getRootPane().getGraphics();  
            // Now draw the image  
            g.drawImage(imageaux, null, 0, 0);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_UnsharActionPerformed

    private void PassaBaixaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassaBaixaIdActionPerformed
        // TODO add your handling code here:
        if(image != null){
            opcao = 2;
            jDialog1.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
        
    }//GEN-LAST:event_PassaBaixaIdActionPerformed

    private void PassaBaixaButterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassaBaixaButterActionPerformed
        // TODO add your handling code here:
        if(image != null){
            opcao = 1;
            jDialog2.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
       
    }//GEN-LAST:event_PassaBaixaButterActionPerformed

    private void PassaBaixaGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassaBaixaGaussActionPerformed
        // TODO add your handling code here:
        if(image != null){
            opcao = 2;
            jDialog1.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_PassaBaixaGaussActionPerformed

    private void PassaAltaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassaAltaIdActionPerformed
        // TODO add your handling code here:
        if(image != null){
            opcao = 3;
            jDialog1.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_PassaAltaIdActionPerformed

    private void PassaAltaButterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassaAltaButterActionPerformed
        // TODO add your handling code here:
        if(image != null){
            opcao = 4;
            jDialog2.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_PassaAltaButterActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         if(image != null){
            opcao = 5;
            jDialog1.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void LaplacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaplacActionPerformed
        // TODO add your handling code here:
        if(image != null){
            int [] dft = new int [h*w];
            int cod = 6;
            int [] argb = new int [h*w];
            int [] img2 = new int [h*w];
            BufferedImage imageaux = image;  
            image.getRGB(0, 0, w, h, argb, 0, w);
        
            img2 = ConverteCinza.imageToGray(argb);
            dft = DFT2.DFTfunc(img2, w, h,cod,5,0,2,0,0);
            imageaux.setRGB(0, 0, w, h, dft , 0, w);
            Graphics2D g = (Graphics2D)ImagemOriginal.getRootPane().getGraphics();  
            // Now draw the image  
            g.drawImage(imageaux, null, 0, 0);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_LaplacActionPerformed

    private void BandRejectIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandRejectIdActionPerformed
        // TODO add your handling code here:
        //jDialog1.setVisible(true); //AQUI
        if(image != null){
            opcao = 8;
            jDialog3.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
       
    }//GEN-LAST:event_BandRejectIdActionPerformed

    private void BandRejectButterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandRejectButterActionPerformed
        // TODO add your handling code here:
        if(image != null){
            opcao = 9;
            jDialog4.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_BandRejectButterActionPerformed

    private void BandRejectGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandRejectGaussActionPerformed
        // TODO add your handling code here:
         if(image != null){
            opcao = 10;
            jDialog3.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_BandRejectGaussActionPerformed

    private void BandPassIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandPassIdActionPerformed
        // TODO add your handling code here:
        if(image != null){
            opcao = 11;
            jDialog3.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_BandPassIdActionPerformed

    private void BandPassButterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandPassButterActionPerformed
        // TODO add your handling code here:
        if(image != null){
            opcao = 12;
            jDialog4.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_BandPassButterActionPerformed

    private void BandPassGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandPassGaussActionPerformed
        // TODO add your handling code here:
        if(image != null){
            opcao = 13;
            jDialog3.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Sem imagem!");
    }//GEN-LAST:event_BandPassGaussActionPerformed

    private void okbuttonD0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonD0ActionPerformed
        // TODO add your handling code here:
        //abro a caixa de diálogo para que seja digitado D0 para o filtro
        jDialog1.setVisible(false);
        
        //AQUI2
        String Aux;
        int [] dft = new int [h*w];
        int cod;
        int [] argb = new int [h*w];
        int [] img2 = new int [h*w];
        BufferedImage imageaux = image; 
        Graphics2D g = (Graphics2D)ResultadoImagem.getRootPane().getGraphics();
        
        Aux = this.ValorD0.getText();
        D0 = Integer.parseInt(Aux);
        switch(opcao){
            case(0):  
                            cod=0; 
                            image.getRGB(0, 0, w, h, argb, 0, w);
                
                            img2 = ConverteCinza.imageToGray(argb);
                            dft = DFT2.DFTfunc(img2, w, h,cod,D0,0,2,0,0);
                            imageaux.setRGB(0, 0, w, h, dft , 0, w);
                             
                            // Now draw the image  
                            g.drawImage(imageaux, null, 0, 0);
                        break;
            case (2):       cod = 2;
                            image.getRGB(0, 0, w, h, argb, 0, w);
                
                            img2 = ConverteCinza.imageToGray(argb);
                            dft = DFT2.DFTfunc(img2, w, h,cod,D0,0,2,0,0);
                            imageaux.setRGB(0, 0, w, h, dft , 0, w);
                            // Now draw the image  
                            g.drawImage(imageaux, null, 0, 0);
                        break; 
                case(3):    cod = 3;
                            image.getRGB(0, 0, w, h, argb, 0, w);
                
                            img2 = ConverteCinza.imageToGray(argb);
                            dft = DFT2.DFTfunc(img2, w, h,cod,D0,0,2,0,0);
                            imageaux.setRGB(0, 0, w, h, dft , 0, w); 
                            // Now draw the image  
                            g.drawImage(imageaux, null, 0, 0);
                        break;
                case(5):    cod = 5;
                            image.getRGB(0, 0, w, h, argb, 0, w);
                
                            img2 = ConverteCinza.imageToGray(argb);
                            dft = DFT2.DFTfunc(img2, w, h,cod,D0,0,2,0,0);
                            imageaux.setRGB(0, 0, w, h, dft , 0, w);
                            // Now draw the image  
                            g.drawImage(imageaux, null, 0, 0);
                        break;  
               case(7):     cod = 7;
                            image.getRGB(0, 0, w, h, argb, 0, w);
                
                            img2 = ConverteCinza.imageToGray(argb);
                            dft = DFT2.DFTfunc(img2, w, h,cod,D0,0,2,0,0);
                            imageaux.setRGB(0, 0, w, h, dft , 0, w);                            
                            // Now draw the image  
                            g.drawImage(imageaux, null, 0, 0);
                        break;
        }       
    }//GEN-LAST:event_okbuttonD0ActionPerformed

    private void OKButtonD0nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonD0nActionPerformed
        // TODO add your handling code here:
        //abro a caixa de diálogo para que seja digitado D0 para o filtro
        jDialog2.setVisible(false);
        String aux;
        int cod;
        int [] dft = new int [h*w];
        int [] argb = new int [h*w];
        int [] img2 = new int [h*w];
        BufferedImage imageaux = image;
                        
        Graphics2D g = (Graphics2D)ResultadoImagem.getRootPane().getGraphics();  
        
        //AQUI2
        aux = this.ValorD0.getText();
        D0 = Integer.parseInt(aux);
        aux = this.n.getText();
        nv = Integer.parseInt(aux);
        
        switch(opcao){
            case(1):    cod =1;  
                        image.getRGB(0, 0, w, h, argb, 0, w);
        
                        img2 = ConverteCinza.imageToGray(argb);
                        dft = DFT2.DFTfunc(img2, w, h,cod,D0,0,nv,0,0);
                        imageaux.setRGB(0, 0, w, h, dft , 0, w);
                        // Now draw the image  
                        g.drawImage(imageaux, null, 0, 0);
                        break;
            case(4):    cod = 4;
                        image.getRGB(0, 0, w, h, argb, 0, w);
        
                        img2 = ConverteCinza.imageToGray(argb);
                        dft = DFT2.DFTfunc(img2, w, h,cod,D0,0,nv,0,0);
                        imageaux.setRGB(0, 0, w, h, dft , 0, w);
                        // Now draw the image  
                        g.drawImage(imageaux, null, 0, 0);  
                        break;
            }
    }//GEN-LAST:event_OKButtonD0nActionPerformed

    private void okbuttonD0WnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonD0WnActionPerformed
        // TODO add your handling code here:
        jDialog4.setVisible(false);
        String aux;
        int cod;
        int [] dft = new int [h*w];
        int [] argb = new int [h*w];
        int [] img2 = new int [h*w];
        BufferedImage imageaux = image;
                        
        Graphics2D g = (Graphics2D)ResultadoImagem.getRootPane().getGraphics();  
        
        //AQUI2
        aux = this.ValorD0.getText();
        D0 = Integer.parseInt(aux);
        aux = this.n.getText();
        nv = Integer.parseInt(aux);
        aux = this.WText.getText();
        W = Integer.parseInt(aux);
        
        switch(opcao){
            case (9):   cod = 9;
                        image.getRGB(0, 0, w, h, argb, 0, w);
        
                        img2 = ConverteCinza.imageToGray(argb);
                        dft = DFT2.DFTfunc(img2, w, h,cod,D0,W,nv,0,0);
                        imageaux.setRGB(0, 0, w, h, dft , 0, w);
                        // Now draw the image  
                        g.drawImage(imageaux, null, 0, 0);  
                        break;
            case(12):   cod =12;
                        image.getRGB(0, 0, w, h, argb, 0, w);
        
                        img2 = ConverteCinza.imageToGray(argb);
                        dft = DFT2.DFTfunc(img2, w, h,cod,D0,W,nv,0,0);
                        imageaux.setRGB(0, 0, w, h, dft , 0, w);
                        // Now draw the image  
                        g.drawImage(imageaux, null, 0, 0);
                        break;
        }
    }//GEN-LAST:event_okbuttonD0WnActionPerformed

    private void WTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WTextActionPerformed

    private void okbuttonD0WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonD0WActionPerformed
        // TODO add your handling code here:
        jDialog3.setVisible(false);
        String aux;
        int cod;
        int [] dft = new int [h*w];
        int [] argb = new int [h*w];
        int [] img2 = new int [h*w];
        BufferedImage imageaux = image;
                        
        Graphics2D g = (Graphics2D)ResultadoImagem.getRootPane().getGraphics();  
        
        //AQUIESTAOPROBLEMA
        aux = this.ValorD0.getText();
        D0 = Integer.parseInt(aux);
        aux = this.WText.getText();
        W = Integer.parseInt(aux);
        
        switch(opcao){
            case (8):   cod = 8;
                        image.getRGB(0, 0, w, h, argb, 0, w);
        
                        img2 = ConverteCinza.imageToGray(argb);
                        dft = DFT2.DFTfunc(img2, w, h,cod,100,50,0,0,0);
                        imageaux.setRGB(0, 0, w, h, dft , 0, w);
                        // Now draw the image  
                        g.drawImage(imageaux, null, 0, 0);  
                        break;
            case(10):   cod =10;
                        image.getRGB(0, 0, w, h, argb, 0, w);
        
                        img2 = ConverteCinza.imageToGray(argb);
                        dft = DFT2.DFTfunc(img2, w, h,cod,100,50,0,0,0);
                        imageaux.setRGB(0, 0, w, h, dft , 0, w);
                        // Now draw the image  
                        g.drawImage(imageaux, null, 0, 0);
                        break;
            case(11):   cod =11;
                        image.getRGB(0, 0, w, h, argb, 0, w);
        
                        img2 = ConverteCinza.imageToGray(argb);
                        dft = DFT2.DFTfunc(img2, w, h,cod,100,50,0,0,0);
                        imageaux.setRGB(0, 0, w, h, dft , 0, w);
                        // Now draw the image  
                        g.drawImage(imageaux, null, 0, 0);
                        break;
            case(13):   cod =13;
                        image.getRGB(0, 0, w, h, argb, 0, w);
        
                        img2 = ConverteCinza.imageToGray(argb);
                        dft = DFT2.DFTfunc(img2, w, h,cod,100,50,0,0,0);
                        imageaux.setRGB(0, 0, w, h, dft , 0, w);
                        // Now draw the image  
                        g.drawImage(imageaux, null, 0, 0);
                        break;
        }
    }//GEN-LAST:event_okbuttonD0WActionPerformed

    private void ValorD0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorD0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorD0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabalho2TelaInicial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabalho2TelaInicial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabalho2TelaInicial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabalho2TelaInicial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabalho2TelaInicial2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BandPassButter;
    private javax.swing.JMenuItem BandPassGauss;
    private javax.swing.JMenuItem BandPassId;
    private javax.swing.JMenuItem BandRejectButter;
    private javax.swing.JMenuItem BandRejectGauss;
    private javax.swing.JMenuItem BandRejectId;
    private javax.swing.JButton CarregaIm;
    private javax.swing.JTextField D0Text;
    private javax.swing.JTextField D0Wn;
    private javax.swing.JTextField D0n;
    public javax.swing.JInternalFrame Espectro;
    private javax.swing.JMenu Filtros;
    private javax.swing.JInternalFrame ImagemOriginal;
    private javax.swing.JMenuItem Laplac;
    private javax.swing.JButton OKButtonD0n;
    private javax.swing.JMenuItem PassaAltaButter;
    private javax.swing.JMenuItem PassaAltaId;
    private javax.swing.JMenuItem PassaBaixaButter;
    private javax.swing.JMenuItem PassaBaixaGauss;
    private javax.swing.JMenuItem PassaBaixaId;
    private javax.swing.JInternalFrame ResultadoImagem;
    private javax.swing.JMenuItem Unshar;
    private javax.swing.JFormattedTextField ValorD0;
    private javax.swing.JTextField WText;
    private javax.swing.JTextField WText2;
    private javax.swing.JFileChooser filechooser;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JTextField n;
    private javax.swing.JTextField nW;
    private javax.swing.JButton okbuttonD0;
    private javax.swing.JButton okbuttonD0W;
    private javax.swing.JButton okbuttonD0Wn;
    // End of variables declaration//GEN-END:variables
}
